### ISSUE TITLE
FEAT: Implement mouse control mode

### ISSUE THREAD

**Issue by world2222** [risi-app/Python-AI#1]
# Description
Brightness and sound can be controlled now. And it'll be looking better if we can control more things, for example, mouse control.
<br>

# Todo
- [x] Implement mouse control mode.
- [x] Implement the logic to distinguish these two modes.
- [x] Fix some codes if it's needed.
